
services:

  companies-service:
    container_name: company-service
    build:
      context: ./company-service
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    networks:
      - hrm-network
    depends_on:
      - company-db
      - discovery-service

  employee-service:
    container_name: employee-service
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    networks:
      - hrm-network
    depends_on:
      - employee-db
      - discovery-service

  config-service:
    container_name: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    networks:
      - hrm-network

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - 8084:8761
    networks:
      - hrm-network
    depends_on:
      - config-service

  company-db:
    container_name: company-db
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - ./volumes/company-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${COMPANY_POSTGRES_DB}
      - POSTGRES_USER=${COMPANY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${COMPANY_POSTGRES_PASSWORD}
    expose:
      - 5433
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hrm-network

  employee-db:
    container_name: employee-db
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - ./volumes/employee-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${EMPLOYEE_POSTGRES_DB}
      - POSTGRES_USER=${EMPLOYEE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${EMPLOYEE_POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hrm-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    restart: always
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    networks:
      - hrm-network
      
networks:
  hrm-network:
    driver: bridge